/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.util.ArrayList;
import java.util.Arrays;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }



    public int someIntegerMethod(int myInt) {
        return myInt + 1;
    }

    public String someStringMethod(String myString){

        return myString;
    }

    public void listStudents() {
        int[] myIntArray = {7,8,9,10};
        String[] studentArray = {"Mike", "Raul", "Chuck", "Roger", "Jon", "Scott", "Abudulahi", "Darius", "Jason"};
        String[] testArr = new String[9];

        ArrayList<Integer> classSizes = new ArrayList<>();
        int class1 = 10;
        int class2 = 20;
        Integer class3 = 30;

        classSizes.add(class1);
        classSizes.add(class2);
        classSizes.add(class3);
        System.out.println("Class sizes: " + classSizes);

        ArrayList<String> students = new ArrayList<>();
//        students.add("Mike");
//        students.add("Raul");

        students.addAll(Arrays.asList(studentArray));

        for(String peeps : students){
            System.out.println("A student: " + peeps);
        }
        System.out.println("arrayList LEngth " + students.size());

//        students.remove(0);

        System.out.println("Students are now: " + students);

        ArrayList<Object> whatsInHere = new ArrayList<>();
        whatsInHere.add(3);
        whatsInHere.add("Hello");

        System.out.println("Whats in here: " + whatsInHere);


    }
}
