/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bakery;

public class App {

    public static void main(String[] args) {
        Bakery raisinFlies = new Bakery();
        System.out.println(raisinFlies.bakedGoods);

        Doughnut myDonut = new Doughnut(false, false, 3.7, 99, "glazed", true);
        System.out.println("MY DONUT: " + myDonut.toString());
        Cake myCake = new Cake(true, false, 0.1, 100, "VCarrot", 8);
        Muffins myMuffin = new Muffins(true, false, 9.2, 6, "Blueberry", true);
//        CinnamonRolls myCinnamonRoll = new CinnamonRolls();


        raisinFlies.bakedGoods.add(myCake);
        BakedGoods item = raisinFlies.bakedGoods.get(0);
        String sttt = myCake.printString();
        System.out.println("STTT: " + sttt );

    }
}
