/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        System.out.println(new App().getGreeting());
        Gson gson = new Gson();

        // primitives
        String myString = "Zork";
        gson.toJson(myString);
        System.out.println("MyString: " + myString);

        Dog zork = new Dog();
        zork.breed="Aussie";
        zork.hasTail = false;


        System.out.println("ZORK: " + gson.toJson(zork));
        // {"breed":"Aussie","size":0,"hasTail":false}

        // let's read in zork.json
        // we need to read(zork.json) with fileReader
        File zorkFile = new File("./app/src/test/resources/zork.json");
        FileReader zorkFileReader = new FileReader(zorkFile);

        Dog newZork = gson.fromJson(zorkFileReader, Dog.class);

        System.out.println("NEWZORK" + newZork.breed);

        // try-with-resources-> AUTOMATIC CLOSING!!!! GOOD DERVELOPER HABITS
        // WINDOWS USERS: your path naming conventions, use -> \\
        File zorkFile2 = new File("./app/src/test/resources/zork2.json");
        try (FileWriter zorkFileWriter = new FileWriter(zorkFile2))
        {
            gson.toJson(newZork, zorkFileWriter);
            System.out.println("DONE");
        }

    }
}
