/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.supertest.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library libraryClassUnderTest = new Library();
        assertTrue(libraryClassUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void someIntegerMethodReturnsPlusOne(){
        Library sut = new Library();
        assertEquals(sut.someIntegerMethod(3), 4, "This test is cool");
    }

    @Test void someStringMethodReturns(){
        Library classUnderTest = new Library();
        assertEquals(classUnderTest.someStringMethod("I Love Zork"), "I Love Zork" );
    }

}
