/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flower;

public class App {

    public static void main(String[] args) {


        //System.out.println(("ARGUMENT FROM THE CMD LINE!!: " + args[0]));
        //System.out.println("ALSO AN ARG: " + args[1]);
        Flower myFlower = new Flower("MyFlower");
        myFlower.name = "Rose";
        System.out.println(myFlower.name);
        myFlower.setLifespan(9);
        System.out.println(myFlower.chopHeight);
        Flower flower1 = new Flower("Flower1");
        Flower flower2 = new Flower("Flower2");
        System.out.println("Flower1 to string: " + flower1.toString());


    }
}
