/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pokeman;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.HttpURLConnection;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    void testCreateRequestWithResponse200() throws IOException {
        // arrange
        Library sut = new Library();
        // act
        HttpURLConnection testHttpURLConnection = sut.createRequest("https://pokeapi.co/api/v2/pokemon/ditto");
        //assert
        assertEquals(200, testHttpURLConnection.getResponseCode());
    }

    @Test
    void testReadResponse() throws IOException{
        // arrange
        Library sut = new Library();
        HttpURLConnection testConnection = sut.createRequest("https://pokeapi.co/api/v2/pokemon/ditto");
        //act
        StringBuffer responseStringBuffer = sut.readResponse(testConnection);
        //assert
        assertNotNull(responseStringBuffer);
    }

    @Test
    void testParsePokemonFromResponse() throws IOException {
        // arrange
        Library sut = new Library();
        HttpURLConnection testConnection = sut.createRequest("https://pokeapi.co/api/v2/pokemon/ditto");
        //act
        StringBuffer responseStringBuffer = sut.readResponse(testConnection);
        Pokemon newPokemon = sut.parsePokemonFromResponse(responseStringBuffer);
        assertEquals(40, newPokemon.weight);
    }
}
